import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "SignUp - Login - Form",
  description: "Generated by Hammad Hafeez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
